# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mainwindow(object):
    def setupUi(self, Mainwindow):
        Mainwindow.setObjectName("Mainwindow")
        Mainwindow.resize(1127, 744)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Năm 3 kỳ 2/bao mat httt/code/GUI/tainguyen/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Mainwindow.setWindowIcon(icon)
        Mainwindow.setWindowOpacity(1.0)
        Mainwindow.setStyleSheet("\n"
"color:black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F6BE5E, stop:0.25 #F8C976, stop:0.5 #FAD794, stop:0.75 #FCE3B4, stop:1 #FDF1D4);\n"
"")
        self.centralwidget = QtWidgets.QWidget(Mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 20, 691, 111))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("font-size: 20px;\n"
"font: 75 18pt \"Montserrat\";\n"
"border: 3px solid #0099FF;\n"
"\n"
"border-radius: 20px;\n"
"color:black;\n"
"\n"
"\n"
"\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 310, 191, 91))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: 3px solid #0099FF;\n"
"font: 16pt \"Montserrat\";\n"
"border-radius:20px;\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 170, 191, 91))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("border-radius:20px;\n"
"background-color:#0099FF;\n"
"border: 3px solid #FF9933;\n"
"font: 75 16pt \"Montserrat\";\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(470, 170, 191, 91))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("border-radius:20px;\n"
"background-color:#0099FF;\n"
"border: 3px solid #FF9933;\n"
"font: 75 16pt \"Montserrat\";\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(690, 170, 191, 91))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("border-radius:20px;\n"
"background-color:#0099FF;\n"
"border: 3px solid #FF9933;\n"
"font: 75 16pt \"Montserrat\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(910, 170, 191, 91))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("border-radius:20px;\n"
"background-color:#0099FF;\n"
"border: 3px solid #FF9933;\n"
"font: 75 16pt \"Montserrat\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 450, 191, 91))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 16pt \"Montserrat\";\n"
"border-radius:20px;\n"
"border: 3px solid #0099FF;\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(250, 310, 411, 91))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("border-radius:20px;\n"
"background-color:#0099FF;\n"
"border: 3px solid #FF9933;\n"
"font: 75 16pt \"Montserrat\";\n"
"\n"
"\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(690, 310, 411, 91))
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setStyleSheet("border-radius:20px;\n"
"background-color:#0099FF;\n"
"border: 3px solid #FF9933;\n"
"font: 75 16pt \"Montserrat\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(470, 450, 191, 91))
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setStyleSheet("border-radius:20px;\n"
"background-color:#0099FF;\n"
"border: 3px solid #FF9933;\n"
"font: 75 16pt \"Montserrat\";\n"
"\n"
"\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(910, 450, 191, 91))
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setStyleSheet("border-radius:20px;\n"
"background-color:#0099FF;\n"
"border: 3px solid #FF9933;\n"
"font: 75 16pt \"Montserrat\";")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(690, 450, 191, 91))
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setStyleSheet("border-radius:20px;\n"
"background-color:#0099FF;\n"
"border: 3px solid #FF9933;\n"
"font: 75 16pt \"Montserrat\";\n"
"\n"
"\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(250, 450, 191, 91))
        self.pushButton_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_10.setStyleSheet("border-radius:20px;\n"
"background-color:#0099FF;\n"
"border: 3px solid #FF9933;\n"
"font: 75 16pt \"Montserrat\";")
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 170, 191, 91))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border: 3px solid #0099FF;\n"
"border-radius:20px;\n"
"font: 16pt \"Montserrat\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 580, 1071, 101))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border: 3px solid #0099FF;\n"
"font: 15pt \"Montserrat\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.pushButton.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.label_3.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.pushButton_9.raise_()
        self.pushButton_10.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        Mainwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Mainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1127, 26))
        self.menubar.setStyleSheet("background-color:white;\n"
"color: black;")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuT_p = QtWidgets.QMenu(self.menubar)
        self.menuT_p.setObjectName("menuT_p")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        Mainwindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Mainwindow)
        self.statusbar.setObjectName("statusbar")
        Mainwindow.setStatusBar(self.statusbar)
        self.actionChuy_n_V = QtWidgets.QAction(Mainwindow)
        self.actionChuy_n_V.setCheckable(False)
        self.actionChuy_n_V.setObjectName("actionChuy_n_V")
        self.actionThay_Th = QtWidgets.QAction(Mainwindow)
        self.actionThay_Th.setObjectName("actionThay_Th")
        self.actionXOR = QtWidgets.QAction(Mainwindow)
        self.actionXOR.setObjectName("actionXOR")
        self.actionTho_t = QtWidgets.QAction(Mainwindow)
        self.actionTho_t.setObjectName("actionTho_t")
        self.actionOpen = QtWidgets.QAction(Mainwindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(Mainwindow)
        self.actionSave.setObjectName("actionSave")
        self.actionWebsite = QtWidgets.QAction(Mainwindow)
        self.actionWebsite.setObjectName("actionWebsite")
        self.actionAbout_us = QtWidgets.QAction(Mainwindow)
        self.actionAbout_us.setObjectName("actionAbout_us")
        self.actionSave_2 = QtWidgets.QAction(Mainwindow)
        self.actionSave_2.setObjectName("actionSave_2")
        self.actionTho_t_2 = QtWidgets.QAction(Mainwindow)
        self.actionTho_t_2.setObjectName("actionTho_t_2")
        self.menuFile.addAction(self.actionChuy_n_V)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionThay_Th)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionXOR)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionTho_t)
        self.menuT_p.addAction(self.actionOpen)
        self.menuT_p.addSeparator()
        self.menuT_p.addAction(self.actionSave)
        self.menuHelp.addAction(self.actionWebsite)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout_us)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuT_p.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Mainwindow)
        QtCore.QMetaObject.connectSlotsByName(Mainwindow)

    def retranslateUi(self, Mainwindow):
        _translate = QtCore.QCoreApplication.translate
        Mainwindow.setWindowTitle(_translate("Mainwindow", "Đồ Án Bảo Mật Hệ Thống Thông Tin"))
        self.label.setText(_translate("Mainwindow", "CÁC THUẬT TOÁN MÃ HÓA CỔ ĐIỂN"))
        self.label_2.setText(_translate("Mainwindow", "Kỹ Thuật \n"
"Thay Thế"))
        self.pushButton.setText(_translate("Mainwindow", "Ceasar"))
        self.pushButton_2.setText(_translate("Mainwindow", "Vigenere"))
        self.pushButton_3.setText(_translate("Mainwindow", "Trithemius"))
        self.pushButton_4.setText(_translate("Mainwindow", "Belasco"))
        self.label_3.setText(_translate("Mainwindow", "Kỹ Thuật \n"
"Chuyển Vị"))
        self.pushButton_5.setText(_translate("Mainwindow", "Chuyển Vị 1 Dòng"))
        self.pushButton_6.setText(_translate("Mainwindow", "Chuyển Vị Nhiều Dòng"))
        self.pushButton_7.setText(_translate("Mainwindow", "Vigenere"))
        self.pushButton_8.setText(_translate("Mainwindow", "Belasco"))
        self.pushButton_9.setText(_translate("Mainwindow", "Trithemius"))
        self.pushButton_10.setText(_translate("Mainwindow", "Ceasar"))
        self.label_4.setText(_translate("Mainwindow", "Kỹ Thuật \n"
"XOR"))
        self.label_5.setText(_translate("Mainwindow", "The System Will BE Upgrade More In The Next Time, Thank You <3\n"
" Lắng nghe giúp chúng tôi hoàn thiện hơn trinhthanhthien.ms365@gmail.com"))
        self.menuFile.setTitle(_translate("Mainwindow", "Mã hóa"))
        self.menuT_p.setTitle(_translate("Mainwindow", "Tệp "))
        self.menuHelp.setTitle(_translate("Mainwindow", "Help"))
        self.actionChuy_n_V.setText(_translate("Mainwindow", "Chuyển Vị"))
        self.actionThay_Th.setText(_translate("Mainwindow", "Thay Thế"))
        self.actionXOR.setText(_translate("Mainwindow", "XOR"))
        self.actionTho_t.setText(_translate("Mainwindow", "Thoát"))
        self.actionOpen.setText(_translate("Mainwindow", "Open"))
        self.actionSave.setText(_translate("Mainwindow", "Save"))
        self.actionWebsite.setText(_translate("Mainwindow", "Website"))
        self.actionAbout_us.setText(_translate("Mainwindow", "About us"))
        self.actionSave_2.setText(_translate("Mainwindow", "Save"))
        self.actionTho_t_2.setText(_translate("Mainwindow", "Thoát"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Mainwindow = QtWidgets.QMainWindow()
    ui = Ui_Mainwindow()
    ui.setupUi(Mainwindow)
    Mainwindow.show()
    sys.exit(app.exec_())
